Display todo count in title
collective/collective.eeafaceted.dashboard pull request #5
Opened 2020-07-31 09:51 UTC by daggelpop

2020-09-02 08:13 UTC, daggelpop commented
Bonjour Stéphan, en voici une.

![Screenshot from 2020-09-02 10-03-06](https://user-images.githubusercontent.com/27828092/91956314-c9d43080-ed04-11ea-8e82-54d824d097d4.png)

Attention: si le total vaut 0, rien n'est affiché dans le titre.

2020-09-02 09:05 UTC, sgeulette commented
ok, je comprends ;-)
Ce que l'on voudrait, c'est afficher ce nombre sur les onglets internes à l'application, à savoir "incoming mail", "outgoing mail" et "tasks", chacun correspondant aux collections que l'onglet contient. 
Il faut aussi une mécanique qui calcule ce nombre pour tous les onglets, même si on ne s'y rend pas. 
L'idée est bien de montrer à un moment qu'il y a tout à coup à gérer quelque chose dans l'onglet tasks par exemple, alors qu'on est ailleurs dans l'application.
Le recalcul peut se faire soit au rafraichissement/affichage d'un page, soit via un cron en arrière plan... À voir ce qui est le moins lourd ou le plus adapté pour cette mécanique. À mon avis la première solution.

2020-09-11 12:46 UTC, sgeulette requested changes
Le rendu est tout à fait ce qu'il nous faut !
En plus de la remarque sur la config, on propose aussi de lier l'action javascript au clic sur une icône "refresh" qu'on placera à droite des onglets. Donc lier le clic à un id css par exemple. Afin d'éviter le recalcul à chaque chargement. C'est l'utilisateur qui fera le refresh quand il le veut...

2020-09-11 12:46 UTC, sgeulette commented on src/collective/eeafaceted/dashboard/browser/static/collective.eeafaceted.dashboard.js
> +    var config = [
On est dans un module générique, il ne faut pas y mettre de config spécifique. 
En accord avec Gauthier, on propose en fait de pouvoir marquer avec une interface les onglets et qu'une vue ajax aille les chercher pour faire ta boucle. tu peux appeler @@json_collections_count directement sur ces dossiers.

2020-09-15 15:27 UTC, daggelpop commented
> Le rendu est tout à fait ce qu'il nous faut !
> En plus de la remarque sur la config, on propose aussi de lier l'action javascript au clic sur une icône "refresh" qu'on placera à droite des onglets. Donc lier le clic à un id css par exemple. Afin d'éviter le recalcul à chaque chargement. C'est l'utilisateur qui fera le refresh quand il le veut...

J'ai ajouté un handler pour _#collections-count-refresh_.
Par contre, je ne vois pas comment insérer proprement l'icône Refresh.

2020-09-15 15:31 UTC, daggelpop commented on src/collective/eeafaceted/dashboard/browser/static/collective.eeafaceted.dashboard.js
> +    var config = [
J'ai fait une pull request pour installer la nouvelle interface _ICountableTab_.
https://github.com/IMIO/imio.dms.mail/pull/2

2020-09-16 13:01 UTC, sgeulette requested changes
unique js function must be separated in 2 different functions: the older one and the new functionality called only on clic AND called when the user enter in the application (login ? or flag true/false in js ?)

2020-09-29 10:10 UTC, sgeulette commented
Corrected some things. Actually useless catalog queries where made too frequently.
Removed not working timer.

2020-09-29 10:12 UTC, merged